version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: trueque_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1323
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
